import 'package:flutter/material.dart';

class Room {
  String roomInfo;
  String tag;
  String title;
  String place;
  String date;
  String time;
  String peopleNum;
  String maxNum;
  String contents;
  String waysToJoin;

  Room({
    required this.roomInfo,
    required this.tag,
    required this.title,
    required this.place,
    required this.date,
    required this.time,
    required this.peopleNum,
    required this.maxNum,
    required this.contents,
    required this.waysToJoin,
  });
}

class Feed {
  String tag;
  String title;
  String place;
  String time;
  String userName;
  String profilePic;
  String date;
  String likeNum;
  String replyNum;
  String contents;

  Feed({
    required this.tag,
    required this.title,
    required this.place,
    required this.time,
    required this.userName,
    required this.profilePic,
    required this.date,
    required this.likeNum,
    required this.replyNum,
    required this.contents,
  });
}

class DataService extends ChangeNotifier {
  List<Room> roomList = [
    Room(
      roomInfo: 'PL',
      tag: '첼시',
      title: '방 제목 입니다1',
      place: '마포구',
      date: '2023-12-24',
      time: '12:24',
      peopleNum: '12',
      maxNum: '30',
      contents: '콘텐츠가 들어가는곳입니다. 길게 쓸수 있어요 길게 길게',
      waysToJoin: '승인제',
    ),
    Room(
      roomInfo: '라리가',
      tag: '첼시',
      title: '방 제목 입니다2',
      place: '여의도동',
      date: '2023-12-25',
      time: '12:25',
      peopleNum: '25',
      maxNum: '30',
      contents:
          '콘텐츠가 들어가는곳입니다. 길게 쓸수 있어요 길게 길게 길게 쓸수 있어요 길게 길게 길게 쓸수 있어요 길게 길게 길게 쓸수 있어요 길게 길게 길게 쓸수 있어요 길게 길게 길게 쓸수 있어요 길게 길게 길게 쓸수 있어요 길게 길게 길게 쓸수 있어요 길게 길게 길게 쓸수 있어요 길게 길게 길게 쓸수 있어요 길게 길게 길게 쓸수 있어요 길게 길게 길게 쓸수 있어요 길게 길게 길게 쓸수 있어요 길게 길게 길게 쓸수 있어요 길게 길게 길게 쓸수 있어요 길게 길게 길게 쓸수 있어요 길게 길게 ',
      waysToJoin: '선착순',
    ),
    Room(
      roomInfo: '세리에A',
      tag: '첼시',
      title: '방 제목 입니다3',
      place: '중구',
      date: '2023-12-26',
      time: '12:26',
      peopleNum: '26',
      maxNum: '30',
      contents:
          '콘텐츠가 들어가는곳입니다. 길게 쓸수 있어요 길게 길게 길게 쓸수 있어요 길게 길게 길게 쓸수 있어요 길게 길게 길게 쓸수 있어요 길게 길게',
      waysToJoin: '승인제',
    ),
  ];

  List<Feed> feedList = [
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다1',
      place: '마포구',
      time: '11:30',
      userName: 'user1',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다2',
      place: '여의도동',
      time: '11:30',
      userName: 'user2',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다3',
      place: '중구',
      time: '11:30',
      userName: 'user3',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다4',
      place: '중구',
      time: '11:30',
      userName: 'user4',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다5',
      place: '중구',
      time: '11:30',
      userName: 'user5',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다6',
      place: '중구',
      time: '11:30',
      userName: 'user6',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다7',
      place: '중구',
      time: '11:30',
      userName: 'user7',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다8',
      place: '중구',
      time: '11:30',
      userName: 'user8',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다9',
      place: '중구',
      time: '11:30',
      userName: 'user9',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다10',
      place: '중구',
      time: '11:30',
      userName: 'user10',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다11',
      place: '마포구',
      time: '11:30',
      userName: 'user11',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다12',
      place: '여의도동',
      time: '11:30',
      userName: 'user12',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다13',
      place: '중구',
      time: '11:30',
      userName: 'user13',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다14',
      place: '중구',
      time: '11:30',
      userName: 'user14',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다15',
      place: '중구',
      time: '11:30',
      userName: 'user15',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다16',
      place: '중구',
      time: '11:30',
      userName: 'user16',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다17',
      place: '중구',
      time: '11:30',
      userName: 'user17',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다18',
      place: '중구',
      time: '11:30',
      userName: 'user8',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다19',
      place: '중구',
      time: '11:30',
      userName: 'user19',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다20',
      place: '중구',
      time: '11:30',
      userName: 'user20',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다21',
      place: '마포구',
      time: '11:30',
      userName: 'user21',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다22',
      place: '여의도동',
      time: '11:30',
      userName: 'user22',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다23',
      place: '중구',
      time: '11:30',
      userName: 'user23',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다24',
      place: '중구',
      time: '11:30',
      userName: 'user24',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다25',
      place: '중구',
      time: '11:30',
      userName: 'user25',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다26',
      place: '중구',
      time: '11:30',
      userName: 'user26',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다27',
      place: '중구',
      time: '11:30',
      userName: 'user27',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다28',
      place: '중구',
      time: '11:30',
      userName: 'user28',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다29',
      place: '중구',
      time: '11:30',
      userName: 'user29',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다30',
      place: '중구',
      time: '11:30',
      userName: 'user30',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다1',
      place: '마포구',
      time: '11:30',
      userName: 'user1',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다2',
      place: '여의도동',
      time: '11:30',
      userName: 'user2',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다3',
      place: '중구',
      time: '11:30',
      userName: 'user3',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다4',
      place: '중구',
      time: '11:30',
      userName: 'user4',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다5',
      place: '중구',
      time: '11:30',
      userName: 'user5',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다6',
      place: '중구',
      time: '11:30',
      userName: 'user6',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다7',
      place: '중구',
      time: '11:30',
      userName: 'user7',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다8',
      place: '중구',
      time: '11:30',
      userName: 'user8',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다9',
      place: '중구',
      time: '11:30',
      userName: 'user9',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다10',
      place: '중구',
      time: '11:30',
      userName: 'user10',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다11',
      place: '마포구',
      time: '11:30',
      userName: 'user11',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다12',
      place: '여의도동',
      time: '11:30',
      userName: 'user12',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다13',
      place: '중구',
      time: '11:30',
      userName: 'user13',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다14',
      place: '중구',
      time: '11:30',
      userName: 'user14',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다15',
      place: '중구',
      time: '11:30',
      userName: 'user15',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다16',
      place: '중구',
      time: '11:30',
      userName: 'user16',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다17',
      place: '중구',
      time: '11:30',
      userName: 'user17',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다18',
      place: '중구',
      time: '11:30',
      userName: 'user8',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다19',
      place: '중구',
      time: '11:30',
      userName: 'user19',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다20',
      place: '중구',
      time: '11:30',
      userName: 'user20',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다21',
      place: '마포구',
      time: '11:30',
      userName: 'user21',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다22',
      place: '여의도동',
      time: '11:30',
      userName: 'user22',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다23',
      place: '중구',
      time: '11:30',
      userName: 'user23',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다24',
      place: '중구',
      time: '11:30',
      userName: 'user24',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다25',
      place: '중구',
      time: '11:30',
      userName: 'user25',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다26',
      place: '중구',
      time: '11:30',
      userName: 'user26',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다27',
      place: '중구',
      time: '11:30',
      userName: 'user27',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다28',
      place: '중구',
      time: '11:30',
      userName: 'user28',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다29',
      place: '중구',
      time: '11:30',
      userName: 'user29',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
    Feed(
      tag: '첼시',
      title: '피드 제목 입니다30',
      place: '중구',
      time: '11:30',
      userName: 'user30',
      profilePic: 'link',
      date: '2023-12-24',
      likeNum: '12',
      replyNum: '25',
      contents: '코멘트가 들어갈 자리입니다. 길게도 쓸수 있는데 더보기 필요함',
    ),
  ];
}
